### ISSUE TITLE
Error in uploading files in Music mastering

### ISSUE THREAD

**Issue by SurabheeSinha** [dolbyio-samples/media-app-react-music-mastering#11]
I was able to generate the proper key-cert pair for access to the app server. However, I am not able to upload any track to the application. I am receiving errors in three different places (that I know of). I have also included screenshots of all three error messages.

When attempting to upload an audio file for mastering....

1. In the frontend GUI, I receive this error message "Upload failed! We're having some trouble uploading your track. Please try again." 
2. Simultaneously, within the front end node.js error log, I receive this message - 
`"[webpack-dev-server] [HPM] Error occurred while proxying request localhost:4200/media/input to https://localhost:3333/ [ECONNREFUSED]`
4. Lastly, within the Chrome web inspect I receive this error indicating some connection is being refused from the app server's end. ("504 Gateway Timeout").
Please advise on the best way to resolve this issue/anything that may be wrong on my end.

[Dolby MasterAI 504 (Gateway Timeout Error) (1).pdf](https://github.com/dolbyio-samples/media-app-react-music-mastering/files/11962206/Dolby.MasterAI.504.Gateway.Timeout.Error.1.pdf)
[Nodejs error (1).pdf](https://github.com/dolbyio-samples/media-app-react-music-mastering/files/11962208/Nodejs.error.1.pdf)
[Screen Shot 2023-06-28 at 8.05.18 PM (1) (1).pdf](https://github.com/dolbyio-samples/media-app-react-music-mastering/files/11962209/Screen.Shot.2023-06-28.at.8.05.18.PM.1.1.pdf)

**Comment by FabienLavocat** [comment]
This issues happens when the proxy server is not started. Please make sure to follow all the steps:

```bash
yarn
yarn build:all
```

**You were probably missing this step:**
Open a terminal window and run the following command to start the backend:
```bash
yarn start:mm-server
```

Open a new terminal window and run the following command to start the frontend: **(Do not close the other terminal)**
```bash
yarn start:mm-sample
```
